plugin: 'gcp_compute'
regions: 'europe-west1'
projects: 'infra-271017'
service_account_file: '../gcloud_av_acount.json'
auth_kind: 'serviceaccount'
hostnames: 'name'
keyed_groups:
  - key: 'zone'
groups:
  stage: "'stage' in name"
  db: "'db' in name"
  app: "'app' in name"

compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
