---
- name: Add Ruby && Bundler
  become: true
  hosts: all
  tasks:

    - name: Install Ruby
      apt: "name={{ item }} state=present"
      with_items:
            - ruby-full
            - ruby-bundler
            - build-essential
